### ISSUE TITLE
Add more logic for when to draw timelines to make larger HAR files look better

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#160] opened 2017-02-23 07:40 UTC
I got some good feedback from @beenanner that we should change how we create those 1 s blue lines. If we have a HAR where the page took long time to load, PerfCascade will only be blue:
<img width="841" alt="screen shot 2017-02-23 at 08 34 48" src="https://cloud.githubusercontent.com/assets/540757/23249114/f8c0c0f6-f9a2-11e6-8903-a27ff4d1db18.png">

Maybe we can have some logic that if the total time is < X seconds, draw a line every second, else every 2 second  or even every 5 second?

I'll see if I can find a good example HAR during the day and attach to the issue.

**Comment by beenanner** [comment] 2017-02-23 14:32
Thanks @soulgalore. :-) Here's the HAR that has 3 runs. The first and third have the delay while the second is under 20 seconds and looks ok. We could just do a simple interval based on 10 and ceiling it?

ex: 
3 / 10 = every 1 sec 
30 / 10  = every 3 sec
60 / 10 = every 6 sec
300 / 10 = every 30 sec

[Long loading HAR](https://gist.github.com/beenanner/93b89d0e81f9e6d469b3d9d230571b60)

**Comment by micmro** [comment] 2017-03-02 13:21
Thanks @beenanner, tried it on a few HARs and your algo worked like a charm.

<img width="716" alt="screen shot 2017-03-02 at 10 15 28 pm" src="https://cloud.githubusercontent.com/assets/1680390/23508714/5c648e96-ff96-11e6-8571-3f5a66c2e91d.png">

**Comment by micmro** [comment] 2017-03-02 13:37
released with `v0.8.0`

**Comment by soulgalore** [comment] 2017-03-02 14:25
I think there was an edge case or some kind of bug in @beenanner HAR (3rd run) that is just little over 30s and get no lines:
<img width="875" alt="screen shot 2017-03-02 at 3 24 02 pm" src="https://cloud.githubusercontent.com/assets/540757/23511083/538904bc-ff5c-11e6-8bc0-f74bd3ab9a8b.png">

**Comment by micmro** [comment] 2017-03-03 01:15
Thanks for testing. Will look into it this weekend.

**Comment by micmro** [comment] 2017-03-04 10:01
Fixed with `v0.8.1` - was caused by some precision errors.

**Closed as completed by micmro** 2017-03-04 10:01 UTC
Labels: enhancement
